export enum PaymentMethod {
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  BANK_DEPOSIT = 'BANK_DEPOSIT',
  CASHIERS_CHECK = 'CASHIERS_CHECK',
  MIXED = 'MIXED',
  FINANCING = 'FINANCING',
  DIGITAL_WALLET = 'DIGITAL_WALLET',
  TRADE_IN = 'TRADE_IN',
  INSTALLMENT_PAYMENT = 'INSTALLMENT_PAYMENT',
}
